include $(GOROOT)/src/Make.inc

TARG=gocodetest
GOFILES=gocodetest.go\
	../ripper.go\
	../apropos.go\
	../autocompletefile.go\
	../autocompletecontext.go\
	../decl.go\
	../package.go\
	../scope.go\
	../declcache.go

include $(GOROOT)/src/Make.cmd
