include $(GOROOT)/src/Make.$(GOARCH)

TARG=gocodetest
GOFILES=gocodetest.go ../ripper.go ../gocodeapropos.go ../file.go ../autocompletion.go ../decl.go ../module.go ../scope.go

include $(GOROOT)/src/Make.cmd
